services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: event_calendar
        MYSQL_USER: my_user
        MYSQL_PASSWORD: password
    volumes:
      - ../mysql-db/sql-scripts:/docker-entrypoint-initdb.d
      - ../mysql-db/mysql-data:/var/lib/mysql
    networks:
        - website-network

  express-app:
    container_name: express-container
    build:
      context: ../express-server
      dockerfile: DockerfileExpress
    ports:
        - "3001:3001"
    depends_on:
      - mysql
    networks:
      - website-network

  react-app:
    container_name: react-container
    build:
      context: ../react-app
      dockerfile: DockerfileReact
    ports:
      - "3000:3000"
    depends_on:
      - express-app
    networks:
      - website-network

volumes:
    mysql-data:

networks:
  website-network:
    driver: bridge